/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    Audio: typeof import('./src/components/userLayout/Audio.vue')['default']
    Avatar: typeof import('./src/components/common/Avatar.vue')['default']
    BackHeader: typeof import('./src/components/common/BackHeader.vue')['default']
    BasicLayout: typeof import('./src/layout/BasicLayout.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChatList: typeof import('./src/components/userLayout/ChatList.vue')['default']
    'ChatList copy': typeof import('./src/components/userLayout/ChatList copy.vue')['default']
    Close: typeof import('./src/components/Close.vue')['default']
    CloseBg: typeof import('./src/components/CloseBg.vue')['default']
    CommentInput: typeof import('./src/components/common/CommentInput.vue')['default']
    Confirm: typeof import('./src/components/common/Confirm/Confirm.vue')['default']
    copy: typeof import('./src/components/userLayout/ChatList copy.vue')['default']
    Dialog: typeof import('./src/components/common/Dialog.vue')['default']
    Dots: typeof import('./src/components/Dots.vue')['default']
    FindList: typeof import('./src/components/FindList.vue')['default']
    Footer: typeof import('./src/components/userLayout/Footer.vue')['default']
    Friend: typeof import('./src/components/Friend.vue')['default']
    HomeList: typeof import('./src/components/HomeList.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    IndexBar: typeof import('./src/components/common/IndexBar.vue')['default']
    Input: typeof import('./src/components/common/Input.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Loading: typeof import('./src/components/common/Loading/Loading.vue')['default']
    Meinfo: typeof import('./src/components/Meinfo.vue')['default']
    Message: typeof import('./src/components/common/Message/Message.vue')['default']
    MeunList: typeof import('./src/components/meunList.vue')['default']
    MomentItem: typeof import('./src/components/MomentItem.vue')['default']
    Mp: typeof import('./src/components/userLayout/mp.vue')['default']
    MsgAudio: typeof import('./src/components/userLayout/msgAudio.vue')['default']
    MyButton: typeof import('./src/components/common/myButton.vue')['default']
    NumberKeyboard: typeof import('./src/components/common/NumberKeyboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanQRCode: typeof import('./src/components/ScanQRCode.vue')['default']
    ScrollLayout: typeof import('./src/layout/ScrollLayout.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchShow: typeof import('./src/components/SearchShow.vue')['default']
    SessionItem: typeof import('./src/components/userLayout/sessionItem.vue')['default']
    ShareSheet: typeof import('./src/components/common/ShareSheet.vue')['default']
    SoundWave: typeof import('./src/components/common/soundWave.vue')['default']
    Swtich: typeof import('./src/components/common/Swtich.vue')['default']
    Text: typeof import('./src/components/common/Text.vue')['default']
    TextItem: typeof import('./src/components/TextItem.vue')['default']
    UserLayout: typeof import('./src/layout/UserLayout.vue')['default']
  }
}
